### PR TITLE
Fixed some spelling errors and tried to improve flow

### PR DESCRIPTION
**Pull request by studdugie**
Hi. I know English is not your first language so in addition to fixing some spelling errors I took the liberty of making some stylistic changes. I hope you don't mind.

### CODE REVIEW

**Comment by agentzh** [comment]
@studdugie Yeah, I know the English there is horrible and just to be clear: it was not from me though ;) I do have plans to rewrite it at some point. Still, I appreciate our original translator :)

**Comment by studdugie** [comment]
Thanks for accepting the patch. This is my second read-through of the text so there may be more patches coming. But if you intend to completely rewrite the tutorial from scratch then I won't send any more.

**Comment by agentzh** [comment]
@studdugie Please do not hesitate to send more patches. Because I may not do the rewrite if it already reads well enough ;)

**Comment by agentzh** [comment]
@studdugie Thank you for your contribution!

**Pull request merged**
